sudo: required
dist: trusty
language: c
matrix:
  fast_finish: true
  include:
    - env: PGVERSION=9.4
    - env: PGVERSION=9.5
    - env: PGVERSION=9.6
    - env: PGVERSION=10
    - env: PGVERSION=11
services:
  - postgresql
script:
  - sudo make install && sudo make installcheck
