language: c
os: linux
addons:
  postgresql: "9.4"
before_install:
  - sudo apt-get update
  - sudo apt-get purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo apt-get install postgresql-client-common postgresql-9.4
  - sudo service postgresql start
script:
  - make install && make installcheck
