sudo: required
dist: trusty
language: c
matrix:
  fast_finish: true
  include:
    - env: PGVERSION=9.4
    - env: PGVERSION=9.5
    - env: PGVERSION=9.6
    - env: PGVERSION=10
    - env: PGVERSION=11
services:
  - postgresql
script:
  - sudo apt-get update && sudo apt-get install -y postgresql postgresql-contrib && sudo service postgresql start
  - sudo make install
